/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckRouteImport } from './routes/check'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShareRouteImport } from './routes/share'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ShareIndexRouteImport } from './routes/share.index'
import { Route as ShareWishlistRouteImport } from './routes/share.wishlist'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareRoute,
} as any)
const ShareWishlistRoute = ShareWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShareRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/wishlist': typeof ShareWishlistRoute
  '/share/': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/wishlist': typeof WishlistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/wishlist': typeof ShareWishlistRoute
  '/share': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check': typeof CheckRoute
  '/login': typeof LoginRoute
  '/share': typeof ShareRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/wishlist': typeof ShareWishlistRoute
  '/share/': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/login'
    | '/share'
    | '/wishlist'
    | '/invite/$token'
    | '/share/wishlist'
    | '/share/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check'
    | '/login'
    | '/wishlist'
    | '/invite/$token'
    | '/share/wishlist'
    | '/share'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/check'
    | '/login'
    | '/share'
    | '/wishlist'
    | '/invite/$token'
    | '/share/wishlist'
    | '/share/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckRoute: typeof CheckRoute
  LoginRoute: typeof LoginRoute
  ShareRoute: typeof ShareRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof ShareRoute
    }
    '/share/wishlist': {
      id: '/share/wishlist'
      path: '/wishlist'
      fullPath: '/share/wishlist'
      preLoaderRoute: typeof ShareWishlistRouteImport
      parentRoute: typeof ShareRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShareRouteChildren {
  ShareWishlistRoute: typeof ShareWishlistRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareWishlistRoute: ShareWishlistRoute,
  ShareIndexRoute: ShareIndexRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckRoute: CheckRoute,
  LoginRoute: LoginRoute,
  ShareRoute: ShareRouteWithChildren,
  WishlistRoute: WishlistRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
